os: linux
language: python
env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - wget ${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda install -y -c conda-forge python=${PYTHONVER} jinja2 requests
script:
  - python run.py --username $USERNAME --token $GH_TOKEN 
  - cp index.html public/index.html
  - cp README.md public/README.md
  - cat packages.md >> public/README.md 
deploy:
  - provider: pages
    token: $GH_TOKEN
    skip_cleanup: true
    local_dir: public
    on:
      branch: master
